version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - veryelite_club
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - veryelite_club
    depends_on:
      - db
  db:
    image: "mongo"
    restart: always
    networks:
      - veryelite_club
    environment:
      MONGODB_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGODB_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    networks:
      - veryelite_club
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - client
      - db


networks:
  veryelite_club:
    external: false
    labels:
      "com.veryeliteclub.description": "veryelite.club network"