#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

SERVICES=(
  api
  client
)
for SERVICE in "${SERVICES[@]}"
do
  if [[ ! -z "$(git status | grep $SERVICE/)" ]]
  then
    echo "Changes found in $SERVICE. Creating sample build."
    yarn --cwd ./$SERVICE run build
  fi
done